---
title: "R Markdown Presentation and Ploty"
author: "Sanjaya J Shetty"
date: "26/11/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Project Objective

1. Create a web page presentation using R Markdown.
2. Presentation should include a plot generated by plotly.
3. The presentation should be hosted on Rpubs, GitHub, or Neocities.

## R code for the Graph

```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(plotly)


plot <- plot_ly(data = mtcars, x=~cyl, y=~mpg, type = "box" )%>%        
    layout(title = "Relationship between Number of Cylinder and Miles per Gallon", 
    xaxis = list(title = "Number of cylinder"), 
    yaxis = list(title = " Miles per Gallon"),
    showlegend = FALSE)
```


## The graph
```{r, message=FALSE, warning=FALSE}
library(plotly)


plot_ly(data = mtcars, x=~cyl, y=~mpg, type = "box" )%>%        
    layout(title = "Relationship between Number of Cylinder and Miles per Gallon", 
    xaxis = list(title = "Number of cylinder"), 
    yaxis = list(title = " Miles per Gallon"),
    showlegend = FALSE)
```
The graph represents the relationship between number of cylinder and MPG. The data for the graph is taken from mtcars.



## Thank you!



