---
title: 'Peer-graded Assignment: R Markdown and Leaflet'
author: "Sanjaya J Shetty"
date: "25/11/2020"
output: html_document
---
# Instruction

### Create a web page using R Markdown that features a map created with Leaflet.

### Host your webpage on either GitHub Pages, RPubs, or NeoCities.

### Your webpage must contain the date that you created the document, and it must contain a map created with Leaflet. We would love to see you show off your creativity!

# Load the librabry

```{r, warning=FALSE, message=FALSE}
library(leaflet)
```

# Create an Icon for the map

```{r}
Taj_Mahal_Icon <- makeIcon(
                  iconUrl = "C:/Users/HP/Downloads/TajMahal.png",
                  iconWidth = 31*215/230, iconHeight =31,
                  iconAnchorX = 31*215/230/2, iconAnchorY = 16
)
```

# The map

```{r}
my_map <- leaflet() %>%
            addTiles() %>%
            addMarkers( lng = 78.0421, lat = 27.1751,icon = Taj_Mahal_Icon, popup = "Taj Mahal - Symbol of LOVE")
                        
my_map
```

